/*
 * Copyright (c) 2025 Ryan Moeller
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#pragma once

#include <ck_pr.h>

/* FIXME: This whole file should be generated by a script. */

/*
 * Legend of Field Identifiers
 *
 * Feature Names - uppercase identifiers as seen in feature test macros
 *   F: Feature (ADD, CAS, ...)
 *   FV: Feature Variant (_VALUE, _ZERO)
 *
 * Function Names - lowercase identifiers as seen in function names
 *   OP: Operation (add, cas, ...)
 *   VARIANT: Operation Variant (_value, _is_zero)
 *
 * Type Names - identifiers as seen in feature test macros and function names
 *   FT: Feature Type (uppercase name)
 *   CKT: Concurrency Kit Type (lowercase name)
 *   CT: C Type (of value)
 *   DT: Delta Type (C type of delta operand)
 *
 * Metadata - additional information about an operation or type
 *   CLASS: Classification (based on operation inputs and outputs)
 *   N: Number (of components of this type in multi-word operations)
 */

/*        F      FV      OP     VARIANT   CLASS               ... */
#define PR_OP_ADD(X, ...) \
	X(ADD,   ,       add,   ,         BINARY_ARITHMETIC,  __VA_ARGS__)
#define PR_OP_AND(X, ...) \
	X(AND,   ,       and,   ,         BINARY_BITWISE,     __VA_ARGS__)
#define PR_OP_BTC(X, ...) \
	X(BTC,   ,       btc,   ,         BIT_RMW,            __VA_ARGS__)
#define PR_OP_BTR(X, ...) \
	X(BTR,   ,       btr,   ,         BIT_RMW,            __VA_ARGS__)
#define PR_OP_BTS(X, ...) \
	X(BTS,   ,       bts,   ,         BIT_RMW,            __VA_ARGS__)
#define PR_OP_CAS(X, ...) \
	X(CAS,   ,       cas,   ,         TERNARY_CAS,        __VA_ARGS__)
#define PR_OP_CAS_VALUE(X, ...) \
	X(CAS,   _VALUE, cas,   _value,   TERNARY_CAS_VALUE,  __VA_ARGS__)
#define PR_OP_DEC(X, ...) \
	X(DEC,   ,       dec,   ,         UNARY_ARITHMETIC,   __VA_ARGS__)
#define PR_OP_DEC_Z(X, ...) \
	X(DEC,   _ZERO,  dec,   _is_zero, UNARY_ARITHMETIC_Z, __VA_ARGS__)
#define PR_OP_FAA(X, ...) \
	X(FAA,   ,       faa,   ,         BINARY_FAA,         __VA_ARGS__)
#define PR_OP_FAS(X, ...) \
	X(FAS,   ,       fas,   ,         BINARY_FAS,         __VA_ARGS__)
#define PR_OP_INC(X, ...) \
	X(INC,   ,       inc,   ,         UNARY_ARITHMETIC,   __VA_ARGS__)
#define PR_OP_INC_Z(X, ...) \
	X(INC,   _ZERO,  inc,   _is_zero, UNARY_ARITHMETIC_Z, __VA_ARGS__)
#define PR_OP_LOAD(X, ...) \
	X(LOAD,  ,       load,  ,         UNARY_LOAD,         __VA_ARGS__)
#define PR_OP_NEG(X, ...) \
	X(NEG,   ,       neg,   ,         UNARY_ARITHMETIC,   __VA_ARGS__)
#define PR_OP_NEG_Z(X, ...) \
	X(NEG,   _ZERO,  neg,   _is_zero, UNARY_ARITHMETIC_Z, __VA_ARGS__)
#define PR_OP_NOT(X, ...) \
	X(NOT,   ,       not,   ,         UNARY_BITWISE,      __VA_ARGS__)
#define PR_OP_OR(X, ...) \
	X(OR,    ,       or,    ,         BINARY_BITWISE,     __VA_ARGS__)
#define PR_OP_STORE(X, ...) \
	X(STORE, ,       store, ,         UNARY_STORE,        __VA_ARGS__)
#define PR_OP_SUB(X, ...) \
	X(SUB,   ,       sub,   ,         BINARY_ARITHMETIC,  __VA_ARGS__)
#define PR_OP_XOR(X, ...) \
	X(XOR,   ,       xor,   ,         BINARY_BITWISE,     __VA_ARGS__)
#define PR_OP_UNIMPLEMENTED(X, ...)

#ifdef CK_F_PR_ADD_8
#define PR_OP_ADD_8 PR_OP_ADD
#else
#define PR_OP_ADD_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_ADD_16
#define PR_OP_ADD_16 PR_OP_ADD
#else
#define PR_OP_ADD_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_ADD_32
#define PR_OP_ADD_32 PR_OP_ADD
#else
#define PR_OP_ADD_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_ADD_64
#define PR_OP_ADD_64 PR_OP_ADD
#else
#define PR_OP_ADD_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_ADD_CHAR
#define PR_OP_ADD_CHAR PR_OP_ADD
#else
#define PR_OP_ADD_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_ADD_DOUBLE
#define PR_OP_ADD_DOUBLE PR_OP_ADD
#else
#define PR_OP_ADD_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_ADD_INT
#define PR_OP_ADD_INT PR_OP_ADD
#else
#define PR_OP_ADD_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_ADD_PTR
#define PR_OP_ADD_PTR PR_OP_ADD
#else
#define PR_OP_ADD_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_ADD_SHORT
#define PR_OP_ADD_SHORT PR_OP_ADD
#else
#define PR_OP_ADD_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_ADD_UINT
#define PR_OP_ADD_UINT PR_OP_ADD
#else
#define PR_OP_ADD_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_AND_8
#define PR_OP_AND_8 PR_OP_AND
#else
#define PR_OP_AND_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_AND_16
#define PR_OP_AND_16 PR_OP_AND
#else
#define PR_OP_AND_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_AND_32
#define PR_OP_AND_32 PR_OP_AND
#else
#define PR_OP_AND_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_AND_64
#define PR_OP_AND_64 PR_OP_AND
#else
#define PR_OP_AND_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_AND_CHAR
#define PR_OP_AND_CHAR PR_OP_AND
#else
#define PR_OP_AND_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_AND_INT
#define PR_OP_AND_INT PR_OP_AND
#else
#define PR_OP_AND_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_AND_PTR
#define PR_OP_AND_PTR PR_OP_AND
#else
#define PR_OP_AND_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_AND_SHORT
#define PR_OP_AND_SHORT PR_OP_AND
#else
#define PR_OP_AND_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_AND_UINT
#define PR_OP_AND_UINT PR_OP_AND
#else
#define PR_OP_AND_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTC_16
#define PR_OP_BTC_16 PR_OP_BTC
#else
#define PR_OP_BTC_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTC_32
#define PR_OP_BTC_32 PR_OP_BTC
#else
#define PR_OP_BTC_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTC_64
#define PR_OP_BTC_64 PR_OP_BTC
#else
#define PR_OP_BTC_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTC_INT
#define PR_OP_BTC_INT PR_OP_BTC
#else
#define PR_OP_BTC_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTC_PTR
#define PR_OP_BTC_PTR PR_OP_BTC
#else
#define PR_OP_BTC_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTC_UINT
#define PR_OP_BTC_UINT PR_OP_BTC
#else
#define PR_OP_BTC_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTR_16
#define PR_OP_BTR_16 PR_OP_BTR
#else
#define PR_OP_BTR_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTR_32
#define PR_OP_BTR_32 PR_OP_BTR
#else
#define PR_OP_BTR_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTR_64
#define PR_OP_BTR_64 PR_OP_BTR
#else
#define PR_OP_BTR_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTR_INT
#define PR_OP_BTR_INT PR_OP_BTR
#else
#define PR_OP_BTR_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTR_PTR
#define PR_OP_BTR_PTR PR_OP_BTR
#else
#define PR_OP_BTR_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTR_UINT
#define PR_OP_BTR_UINT PR_OP_BTR
#else
#define PR_OP_BTR_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTS_16
#define PR_OP_BTS_16 PR_OP_BTS
#else
#define PR_OP_BTS_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTS_32
#define PR_OP_BTS_32 PR_OP_BTS
#else
#define PR_OP_BTS_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTS_64
#define PR_OP_BTS_64 PR_OP_BTS
#else
#define PR_OP_BTS_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTS_INT
#define PR_OP_BTS_INT PR_OP_BTS
#else
#define PR_OP_BTS_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTS_PTR
#define PR_OP_BTS_PTR PR_OP_BTS
#else
#define PR_OP_BTS_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_BTS_UINT
#define PR_OP_BTS_UINT PR_OP_BTS
#else
#define PR_OP_BTS_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_8
#define PR_OP_CAS_8 PR_OP_CAS
#else
#define PR_OP_CAS_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_8_VALUE
#define PR_OP_CAS_VALUE_8 PR_OP_CAS_VALUE
#else
#define PR_OP_CAS_VALUE_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_16
#define PR_OP_CAS_16 PR_OP_CAS
#else
#define PR_OP_CAS_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_16_VALUE
#define PR_OP_CAS_VALUE_16 PR_OP_CAS_VALUE
#else
#define PR_OP_CAS_VALUE_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_32
#define PR_OP_CAS_32 PR_OP_CAS
#else
#define PR_OP_CAS_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_32_VALUE
#define PR_OP_CAS_VALUE_32 PR_OP_CAS_VALUE
#else
#define PR_OP_CAS_VALUE_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_64
#define PR_OP_CAS_64 PR_OP_CAS
#else
#define PR_OP_CAS_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_64_VALUE
#define PR_OP_CAS_VALUE_64 PR_OP_CAS_VALUE
#else
#define PR_OP_CAS_VALUE_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_CHAR
#define PR_OP_CAS_CHAR PR_OP_CAS
#else
#define PR_OP_CAS_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_CHAR_VALUE
#define PR_OP_CAS_VALUE_CHAR PR_OP_CAS_VALUE
#else
#define PR_OP_CAS_VALUE_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_DOUBLE
#define PR_OP_CAS_DOUBLE PR_OP_CAS
#else
#define PR_OP_CAS_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_DOUBLE_VALUE
#define PR_OP_CAS_VALUE_DOUBLE PR_OP_CAS_VALUE
#else
#define PR_OP_CAS_VALUE_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_INT
#define PR_OP_CAS_INT PR_OP_CAS
#else
#define PR_OP_CAS_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_INT_VALUE
#define PR_OP_CAS_VALUE_INT PR_OP_CAS_VALUE
#else
#define PR_OP_CAS_VALUE_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_PTR
#define PR_OP_CAS_PTR PR_OP_CAS
#else
#define PR_OP_CAS_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_PTR_VALUE
#define PR_OP_CAS_VALUE_PTR PR_OP_CAS_VALUE
#else
#define PR_OP_CAS_VALUE_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_SHORT
#define PR_OP_CAS_SHORT PR_OP_CAS
#else
#define PR_OP_CAS_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_SHORT_VALUE
#define PR_OP_CAS_VALUE_SHORT PR_OP_CAS_VALUE
#else
#define PR_OP_CAS_VALUE_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_UINT
#define PR_OP_CAS_UINT PR_OP_CAS
#else
#define PR_OP_CAS_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_UINT_VALUE
#define PR_OP_CAS_VALUE_UINT PR_OP_CAS_VALUE
#else
#define PR_OP_CAS_VALUE_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_8
#define PR_OP_DEC_8 PR_OP_DEC
#else
#define PR_OP_DEC_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_8_ZERO
#define PR_OP_DEC_Z_8 PR_OP_DEC_Z
#else
#define PR_OP_DEC_Z_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_16
#define PR_OP_DEC_16 PR_OP_DEC
#else
#define PR_OP_DEC_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_16_ZERO
#define PR_OP_DEC_Z_16 PR_OP_DEC_Z
#else
#define PR_OP_DEC_Z_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_32
#define PR_OP_DEC_32 PR_OP_DEC
#else
#define PR_OP_DEC_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_32_ZERO
#define PR_OP_DEC_Z_32 PR_OP_DEC_Z
#else
#define PR_OP_DEC_Z_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_64
#define PR_OP_DEC_64 PR_OP_DEC
#else
#define PR_OP_DEC_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_64_ZERO
#define PR_OP_DEC_Z_64 PR_OP_DEC_Z
#else
#define PR_OP_DEC_Z_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_CHAR
#define PR_OP_DEC_CHAR PR_OP_DEC
#else
#define PR_OP_DEC_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_CHAR_ZERO
#define PR_OP_DEC_Z_CHAR PR_OP_DEC_Z
#else
#define PR_OP_DEC_Z_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_DOUBLE
#define PR_OP_DEC_DOUBLE PR_OP_DEC
#else
#define PR_OP_DEC_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_INT
#define PR_OP_DEC_INT PR_OP_DEC
#else
#define PR_OP_DEC_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_INT_ZERO
#define PR_OP_DEC_Z_INT PR_OP_DEC_Z
#else
#define PR_OP_DEC_Z_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_PTR
#define PR_OP_DEC_PTR PR_OP_DEC
#else
#define PR_OP_DEC_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_PTR_ZERO
#define PR_OP_DEC_Z_PTR PR_OP_DEC_Z
#else
#define PR_OP_DEC_Z_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_SHORT
#define PR_OP_DEC_SHORT PR_OP_DEC
#else
#define PR_OP_DEC_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_SHORT_ZERO
#define PR_OP_DEC_Z_SHORT PR_OP_DEC_Z
#else
#define PR_OP_DEC_Z_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_UINT
#define PR_OP_DEC_UINT PR_OP_DEC
#else
#define PR_OP_DEC_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_DEC_UINT_ZERO
#define PR_OP_DEC_Z_UINT PR_OP_DEC_Z
#else
#define PR_OP_DEC_Z_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAA_8
#define PR_OP_FAA_8 PR_OP_FAA
#else
#define PR_OP_FAA_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAA_16
#define PR_OP_FAA_16 PR_OP_FAA
#else
#define PR_OP_FAA_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAA_32
#define PR_OP_FAA_32 PR_OP_FAA
#else
#define PR_OP_FAA_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAA_64
#define PR_OP_FAA_64 PR_OP_FAA
#else
#define PR_OP_FAA_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAA_CHAR
#define PR_OP_FAA_CHAR PR_OP_FAA
#else
#define PR_OP_FAA_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAA_DOUBLE
#define PR_OP_FAA_DOUBLE PR_OP_FAA
#else
#define PR_OP_FAA_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAA_INT
#define PR_OP_FAA_INT PR_OP_FAA
#else
#define PR_OP_FAA_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAA_PTR
#define PR_OP_FAA_PTR PR_OP_FAA
#else
#define PR_OP_FAA_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAA_SHORT
#define PR_OP_FAA_SHORT PR_OP_FAA
#else
#define PR_OP_FAA_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAA_UINT
#define PR_OP_FAA_UINT PR_OP_FAA
#else
#define PR_OP_FAA_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAS_8
#define PR_OP_FAS_8 PR_OP_FAS
#else
#define PR_OP_FAS_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAS_16
#define PR_OP_FAS_16 PR_OP_FAS
#else
#define PR_OP_FAS_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAS_32
#define PR_OP_FAS_32 PR_OP_FAS
#else
#define PR_OP_FAS_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAS_64
#define PR_OP_FAS_64 PR_OP_FAS
#else
#define PR_OP_FAS_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAS_CHAR
#define PR_OP_FAS_CHAR PR_OP_FAS
#else
#define PR_OP_FAS_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAS_DOUBLE
#define PR_OP_FAS_DOUBLE PR_OP_FAS
#else
#define PR_OP_FAS_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAS_INT
#define PR_OP_FAS_INT PR_OP_FAS
#else
#define PR_OP_FAS_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAS_PTR
#define PR_OP_FAS_PTR PR_OP_FAS
#else
#define PR_OP_FAS_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAS_SHORT
#define PR_OP_FAS_SHORT PR_OP_FAS
#else
#define PR_OP_FAS_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_FAS_UINT
#define PR_OP_FAS_UINT PR_OP_FAS
#else
#define PR_OP_FAS_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_8
#define PR_OP_INC_8 PR_OP_INC
#else
#define PR_OP_INC_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_8_ZERO
#define PR_OP_INC_Z_8 PR_OP_INC_Z
#else
#define PR_OP_INC_Z_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_16
#define PR_OP_INC_16 PR_OP_INC
#else
#define PR_OP_INC_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_16_ZERO
#define PR_OP_INC_Z_16 PR_OP_INC_Z
#else
#define PR_OP_INC_Z_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_32
#define PR_OP_INC_32 PR_OP_INC
#else
#define PR_OP_INC_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_32_ZERO
#define PR_OP_INC_Z_32 PR_OP_INC_Z
#else
#define PR_OP_INC_Z_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_64
#define PR_OP_INC_64 PR_OP_INC
#else
#define PR_OP_INC_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_64_ZERO
#define PR_OP_INC_Z_64 PR_OP_INC_Z
#else
#define PR_OP_INC_Z_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_CHAR
#define PR_OP_INC_CHAR PR_OP_INC
#else
#define PR_OP_INC_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_CHAR_ZERO
#define PR_OP_INC_Z_CHAR PR_OP_INC_Z
#else
#define PR_OP_INC_Z_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_DOUBLE
#define PR_OP_INC_DOUBLE PR_OP_INC
#else
#define PR_OP_INC_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_INT
#define PR_OP_INC_INT PR_OP_INC
#else
#define PR_OP_INC_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_INT_ZERO
#define PR_OP_INC_Z_INT PR_OP_INC_Z
#else
#define PR_OP_INC_Z_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_PTR
#define PR_OP_INC_PTR PR_OP_INC
#else
#define PR_OP_INC_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_PTR_ZERO
#define PR_OP_INC_Z_PTR PR_OP_INC_Z
#else
#define PR_OP_INC_Z_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_SHORT
#define PR_OP_INC_SHORT PR_OP_INC
#else
#define PR_OP_INC_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_SHORT_ZERO
#define PR_OP_INC_Z_SHORT PR_OP_INC_Z
#else
#define PR_OP_INC_Z_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_UINT
#define PR_OP_INC_UINT PR_OP_INC
#else
#define PR_OP_INC_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_INC_UINT_ZERO
#define PR_OP_INC_Z_UINT PR_OP_INC_Z
#else
#define PR_OP_INC_Z_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_8
#define PR_OP_LOAD_8 PR_OP_LOAD
#else
#define PR_OP_LOAD_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_16
#define PR_OP_LOAD_16 PR_OP_LOAD
#else
#define PR_OP_LOAD_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_32
#define PR_OP_LOAD_32 PR_OP_LOAD
#else
#define PR_OP_LOAD_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_64
#define PR_OP_LOAD_64 PR_OP_LOAD
#else
#define PR_OP_LOAD_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_CHAR
#define PR_OP_LOAD_CHAR PR_OP_LOAD
#else
#define PR_OP_LOAD_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_DOUBLE
#define PR_OP_LOAD_DOUBLE PR_OP_LOAD
#else
#define PR_OP_LOAD_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_INT
#define PR_OP_LOAD_INT PR_OP_LOAD
#else
#define PR_OP_LOAD_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_PTR
#define PR_OP_LOAD_PTR PR_OP_LOAD
#else
#define PR_OP_LOAD_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_SHORT
#define PR_OP_LOAD_SHORT PR_OP_LOAD
#else
#define PR_OP_LOAD_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_UINT
#define PR_OP_LOAD_UINT PR_OP_LOAD
#else
#define PR_OP_LOAD_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_8
#define PR_OP_NEG_8 PR_OP_NEG
#else
#define PR_OP_NEG_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_8_ZERO
#define PR_OP_NEG_Z_8 PR_OP_NEG_Z
#else
#define PR_OP_NEG_Z_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_16
#define PR_OP_NEG_16 PR_OP_NEG
#else
#define PR_OP_NEG_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_16_ZERO
#define PR_OP_NEG_Z_16 PR_OP_NEG_Z
#else
#define PR_OP_NEG_Z_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_32
#define PR_OP_NEG_32 PR_OP_NEG
#else
#define PR_OP_NEG_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_32_ZERO
#define PR_OP_NEG_Z_32 PR_OP_NEG_Z
#else
#define PR_OP_NEG_Z_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_64
#define PR_OP_NEG_64 PR_OP_NEG
#else
#define PR_OP_NEG_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_64_ZERO
#define PR_OP_NEG_Z_64 PR_OP_NEG_Z
#else
#define PR_OP_NEG_Z_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_CHAR
#define PR_OP_NEG_CHAR PR_OP_NEG
#else
#define PR_OP_NEG_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_CHAR_ZERO
#define PR_OP_NEG_Z_CHAR PR_OP_NEG_Z
#else
#define PR_OP_NEG_Z_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_DOUBLE
#define PR_OP_NEG_DOUBLE PR_OP_NEG
#else
#define PR_OP_NEG_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_INT
#define PR_OP_NEG_INT PR_OP_NEG
#else
#define PR_OP_NEG_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_INT_ZERO
#define PR_OP_NEG_Z_INT PR_OP_NEG_Z
#else
#define PR_OP_NEG_Z_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_PTR
#define PR_OP_NEG_PTR PR_OP_NEG
#else
#define PR_OP_NEG_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_PTR_ZERO
#define PR_OP_NEG_Z_PTR PR_OP_NEG_Z
#else
#define PR_OP_NEG_Z_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_SHORT
#define PR_OP_NEG_SHORT PR_OP_NEG
#else
#define PR_OP_NEG_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_SHORT_ZERO
#define PR_OP_NEG_Z_SHORT PR_OP_NEG_Z
#else
#define PR_OP_NEG_Z_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_UINT
#define PR_OP_NEG_UINT PR_OP_NEG
#else
#define PR_OP_NEG_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NEG_UINT_ZERO
#define PR_OP_NEG_Z_UINT PR_OP_NEG_Z
#else
#define PR_OP_NEG_Z_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NOT_8
#define PR_OP_NOT_8 PR_OP_NOT
#else
#define PR_OP_NOT_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NOT_16
#define PR_OP_NOT_16 PR_OP_NOT
#else
#define PR_OP_NOT_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NOT_32
#define PR_OP_NOT_32 PR_OP_NOT
#else
#define PR_OP_NOT_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NOT_64
#define PR_OP_NOT_64 PR_OP_NOT
#else
#define PR_OP_NOT_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NOT_CHAR
#define PR_OP_NOT_CHAR PR_OP_NOT
#else
#define PR_OP_NOT_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NOT_INT
#define PR_OP_NOT_INT PR_OP_NOT
#else
#define PR_OP_NOT_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NOT_PTR
#define PR_OP_NOT_PTR PR_OP_NOT
#else
#define PR_OP_NOT_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NOT_SHORT
#define PR_OP_NOT_SHORT PR_OP_NOT
#else
#define PR_OP_NOT_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_NOT_UINT
#define PR_OP_NOT_UINT PR_OP_NOT
#else
#define PR_OP_NOT_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_OR_8
#define PR_OP_OR_8 PR_OP_OR
#else
#define PR_OP_OR_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_OR_16
#define PR_OP_OR_16 PR_OP_OR
#else
#define PR_OP_OR_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_OR_32
#define PR_OP_OR_32 PR_OP_OR
#else
#define PR_OP_OR_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_OR_64
#define PR_OP_OR_64 PR_OP_OR
#else
#define PR_OP_OR_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_OR_CHAR
#define PR_OP_OR_CHAR PR_OP_OR
#else
#define PR_OP_OR_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_OR_INT
#define PR_OP_OR_INT PR_OP_OR
#else
#define PR_OP_OR_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_OR_PTR
#define PR_OP_OR_PTR PR_OP_OR
#else
#define PR_OP_OR_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_OR_SHORT
#define PR_OP_OR_SHORT PR_OP_OR
#else
#define PR_OP_OR_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_OR_UINT
#define PR_OP_OR_UINT PR_OP_OR
#else
#define PR_OP_OR_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_STORE_8
#define PR_OP_STORE_8 PR_OP_STORE
#else
#define PR_OP_STORE_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_STORE_16
#define PR_OP_STORE_16 PR_OP_STORE
#else
#define PR_OP_STORE_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_STORE_32
#define PR_OP_STORE_32 PR_OP_STORE
#else
#define PR_OP_STORE_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_STORE_64
#define PR_OP_STORE_64 PR_OP_STORE
#else
#define PR_OP_STORE_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_STORE_CHAR
#define PR_OP_STORE_CHAR PR_OP_STORE
#else
#define PR_OP_STORE_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_STORE_DOUBLE
#define PR_OP_STORE_DOUBLE PR_OP_STORE
#else
#define PR_OP_STORE_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_STORE_INT
#define PR_OP_STORE_INT PR_OP_STORE
#else
#define PR_OP_STORE_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_STORE_PTR
#define PR_OP_STORE_PTR PR_OP_STORE
#else
#define PR_OP_STORE_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_STORE_SHORT
#define PR_OP_STORE_SHORT PR_OP_STORE
#else
#define PR_OP_STORE_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_STORE_UINT
#define PR_OP_STORE_UINT PR_OP_STORE
#else
#define PR_OP_STORE_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_SUB_8
#define PR_OP_SUB_8 PR_OP_SUB
#else
#define PR_OP_SUB_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_SUB_16
#define PR_OP_SUB_16 PR_OP_SUB
#else
#define PR_OP_SUB_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_SUB_32
#define PR_OP_SUB_32 PR_OP_SUB
#else
#define PR_OP_SUB_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_SUB_64
#define PR_OP_SUB_64 PR_OP_SUB
#else
#define PR_OP_SUB_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_SUB_CHAR
#define PR_OP_SUB_CHAR PR_OP_SUB
#else
#define PR_OP_SUB_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_SUB_DOUBLE
#define PR_OP_SUB_DOUBLE PR_OP_SUB
#else
#define PR_OP_SUB_DOUBLE PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_SUB_INT
#define PR_OP_SUB_INT PR_OP_SUB
#else
#define PR_OP_SUB_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_SUB_PTR
#define PR_OP_SUB_PTR PR_OP_SUB
#else
#define PR_OP_SUB_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_SUB_SHORT
#define PR_OP_SUB_SHORT PR_OP_SUB
#else
#define PR_OP_SUB_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_SUB_UINT
#define PR_OP_SUB_UINT PR_OP_SUB
#else
#define PR_OP_SUB_UINT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_XOR_8
#define PR_OP_XOR_8 PR_OP_XOR
#else
#define PR_OP_XOR_8 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_XOR_16
#define PR_OP_XOR_16 PR_OP_XOR
#else
#define PR_OP_XOR_16 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_XOR_32
#define PR_OP_XOR_32 PR_OP_XOR
#else
#define PR_OP_XOR_32 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_XOR_64
#define PR_OP_XOR_64 PR_OP_XOR
#else
#define PR_OP_XOR_64 PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_XOR_CHAR
#define PR_OP_XOR_CHAR PR_OP_XOR
#else
#define PR_OP_XOR_CHAR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_XOR_INT
#define PR_OP_XOR_INT PR_OP_XOR
#else
#define PR_OP_XOR_INT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_XOR_PTR
#define PR_OP_XOR_PTR PR_OP_XOR
#else
#define PR_OP_XOR_PTR PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_XOR_SHORT
#define PR_OP_XOR_SHORT PR_OP_XOR
#else
#define PR_OP_XOR_SHORT PR_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_XOR_UINT
#define PR_OP_XOR_UINT PR_OP_XOR
#else
#define PR_OP_XOR_UINT PR_OP_UNIMPLEMENTED
#endif

#define PR_OPS_GROUP1(X, ...) \
	X(ADD, __VA_ARGS__) \
	X(CAS, __VA_ARGS__) \
	X(CAS_VALUE, __VA_ARGS__) \
	X(DEC, __VA_ARGS__) \
	X(FAA, __VA_ARGS__) \
	X(FAS, __VA_ARGS__) \
	X(INC, __VA_ARGS__) \
	X(LOAD, __VA_ARGS__) \
	X(NEG, __VA_ARGS__) \
	X(STORE, __VA_ARGS__) \
	X(SUB, __VA_ARGS__)

#define PR_OPS_GROUP2(X, ...) \
	X(ADD, __VA_ARGS__) \
	X(AND, __VA_ARGS__) \
	X(CAS, __VA_ARGS__) \
	X(CAS_VALUE, __VA_ARGS__) \
	X(DEC, __VA_ARGS__) \
	X(DEC_Z, __VA_ARGS__) \
	X(FAA, __VA_ARGS__) \
	X(FAS, __VA_ARGS__) \
	X(INC, __VA_ARGS__) \
	X(INC_Z, __VA_ARGS__) \
	X(LOAD, __VA_ARGS__) \
	X(NEG, __VA_ARGS__) \
	X(NEG_Z, __VA_ARGS__) \
	X(NOT, __VA_ARGS__) \
	X(OR, __VA_ARGS__) \
	X(STORE, __VA_ARGS__) \
	X(SUB, __VA_ARGS__) \
	X(XOR, __VA_ARGS__)

#define PR_OPS_GROUP3(X, ...) \
	X(ADD, __VA_ARGS__) \
	X(AND, __VA_ARGS__) \
	X(BTC, __VA_ARGS__) \
	X(BTR, __VA_ARGS__) \
	X(BTS, __VA_ARGS__) \
	X(CAS, __VA_ARGS__) \
	X(CAS_VALUE, __VA_ARGS__) \
	X(DEC, __VA_ARGS__) \
	X(DEC_Z, __VA_ARGS__) \
	X(FAA, __VA_ARGS__) \
	X(FAS, __VA_ARGS__) \
	X(INC, __VA_ARGS__) \
	X(INC_Z, __VA_ARGS__) \
	X(LOAD, __VA_ARGS__) \
	X(NEG, __VA_ARGS__) \
	X(NEG_Z, __VA_ARGS__) \
	X(NOT, __VA_ARGS__) \
	X(OR, __VA_ARGS__) \
	X(STORE, __VA_ARGS__) \
	X(SUB, __VA_ARGS__) \
	X(XOR, __VA_ARGS__)

#define PR_OP_EXPANDER(OP, X, ...) \
	PR_OP_##OP(X, __VA_ARGS__)

#define PR_OPS_LIST(X, ...) \
	PR_OPS_GROUP3(PR_OP_EXPANDER, X, __VA_ARGS__)

#define PR_8_OPS_LIST      PR_OPS_GROUP2
#define PR_16_OPS_LIST     PR_OPS_GROUP3
#define PR_32_OPS_LIST     PR_OPS_GROUP3
#define PR_64_OPS_LIST     PR_OPS_GROUP3
#define PR_CHAR_OPS_LIST   PR_OPS_GROUP2
#define PR_DOUBLE_OPS_LIST PR_OPS_GROUP1
#define PR_INT_OPS_LIST    PR_OPS_GROUP3
#define PR_PTR_OPS_LIST    PR_OPS_GROUP3
#define PR_SHORT_OPS_LIST  PR_OPS_GROUP2
#define PR_UINT_OPS_LIST   PR_OPS_GROUP3

/*         FT                 CKT     CT            DT            ... */
#define PR_8_T(X, ...)      X(8,      uint8_t,      uint8_t,      __VA_ARGS__)
#define PR_16_T(X, ...)     X(16,     uint16_t,     uint16_t,     __VA_ARGS__)
#define PR_32_T(X, ...)     X(32,     uint32_t,     uint32_t,     __VA_ARGS__)
#define PR_64_T(X, ...)     X(64,     uint64_t,     uint64_t,     __VA_ARGS__)
#define PR_CHAR_T(X, ...)   X(char,   char,         char,         __VA_ARGS__)
#define PR_DOUBLE_T(X, ...) X(double, double,       double,       __VA_ARGS__)
#define PR_INT_T(X, ...)    X(int,    int,          int,          __VA_ARGS__)
#define PR_PTR_T(X, ...)    X(ptr,    void *,       uintptr_t,    __VA_ARGS__)
#define PR_SHORT_T(X, ...)  X(short,  short,        short,        __VA_ARGS__)
#define PR_UINT_T(X, ...)   X(uint,   unsigned int, unsigned int, __VA_ARGS__)

/*        FT      ... */
#define PR_F_TYPES_LIST(X, ...) \
	X(8,      __VA_ARGS__) \
	X(16,     __VA_ARGS__) \
	X(32,     __VA_ARGS__) \
	X(64,     __VA_ARGS__) \
	X(CHAR,   __VA_ARGS__) \
	X(DOUBLE, __VA_ARGS__) \
	X(INT,    __VA_ARGS__) \
	X(PTR,    __VA_ARGS__) \
	X(SHORT,  __VA_ARGS__) \
	X(UINT,   __VA_ARGS__)

#define PR_T_EXPANDER(FT, X, ...) \
	PR_##FT##_T(X, FT, __VA_ARGS__)

#define PR_TYPES_LIST(X, ...) \
	PR_F_TYPES_LIST(PR_T_EXPANDER, X, __VA_ARGS__)

/*
 * 128-bit ops
 *
 *        F     FV      N  OP    VARIANT CLASS             ...
 */
#define PR128_OP_CAS_N(X, N, ...) \
	X(CAS,  ,       N, cas,  ,       TERNARY_CAS,       __VA_ARGS__)
#define PR128_OP_CAS_VALUE_N(X, N, ...) \
	X(CAS,  _VALUE, N, cas,  _value, TERNARY_CAS_VALUE, __VA_ARGS__)
#define PR128_OP_LOAD_N(X, N, ...) \
	X(LOAD, ,       N, load, ,       UNARY_LOAD,        __VA_ARGS__)

#define PR128_OP_CAS_2(X, ...) \
	PR128_OP_CAS_N(X, 2, __VA_ARGS__)
#define PR128_OP_CAS_VALUE_2(X, ...) \
	PR128_OP_CAS_VALUE_N(X, 2, __VA_ARGS__)
#define PR128_OP_LOAD_2(X, ...) \
	PR128_OP_LOAD_N(X, 2, __VA_ARGS__)

#define PR128_OP_CAS_4(X, ...) \
	PR128_OP_CAS_N(X, 4, __VA_ARGS__)
#define PR128_OP_CAS_VALUE_4(X, ...) \
	PR128_OP_CAS_VALUE_N(X, 4, __VA_ARGS__)
#define PR128_OP_LOAD_4(X, ...) \
	PR128_OP_LOAD_N(X, 4, __VA_ARGS__)

#define PR128_OP_CAS_8(X, ...) \
	PR128_OP_CAS_N(X, 8, __VA_ARGS__)
#define PR128_OP_CAS_VALUE_8(X, ...) \
	PR128_OP_CAS_VALUE_N(X, 8, __VA_ARGS__)
#define PR128_OP_LOAD_8(X, ...) \
	PR128_OP_LOAD_N(X, 8, __VA_ARGS__)

#define PR128_OP_CAS_16(X, ...) \
	PR128_OP_CAS_N(X, 16, __VA_ARGS__)
#define PR128_OP_CAS_VALUE_16(X, ...) \
	PR128_OP_CAS_VALUE_N(X, 16, __VA_ARGS__)
#define PR128_OP_LOAD_16(X, ...) \
	PR128_OP_LOAD_N(X, 16, __VA_ARGS__)

#define PR128_OP_UNIMPLEMENTED(X, ...)

#ifdef CK_F_PR_CAS_8_16
#define PR128_OP_CAS_16_8 PR128_OP_CAS_16
#else
#define PR128_OP_CAS_16_8 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_8_16_VALUE
#define PR128_OP_CAS_VALUE_16_8 PR128_OP_CAS_VALUE_16
#else
#define PR128_OP_CAS_VALUE_16_8 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_16_8
#define PR128_OP_CAS_8_16 PR128_OP_CAS_8
#else
#define PR128_OP_CAS_8_16 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_16_8_VALUE
#define PR128_OP_CAS_VALUE_8_16 PR128_OP_CAS_VALUE_8
#else
#define PR128_OP_CAS_VALUE_8_16 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_32_4
#define PR128_OP_CAS_4_32 PR128_OP_CAS_4
#else
#define PR128_OP_CAS_4_32 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_32_4_VALUE
#define PR128_OP_CAS_VALUE_4_32 PR128_OP_CAS_VALUE_4
#else
#define PR128_OP_CAS_VALUE_4_32 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_64_2
#define PR128_OP_CAS_2_64 PR128_OP_CAS_2
#else
#define PR128_OP_CAS_2_64 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_64_2_VALUE
#define PR128_OP_CAS_VALUE_2_64 PR128_OP_CAS_VALUE_2
#else
#define PR128_OP_CAS_VALUE_2_64 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_CHAR_16
#define PR128_OP_CAS_16_CHAR PR128_OP_CAS_16
#else
#define PR128_OP_CAS_16_CHAR PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_CHAR_16_VALUE
#define PR128_OP_CAS_VALUE_16_CHAR PR128_OP_CAS_VALUE_16
#else
#define PR128_OP_CAS_VALUE_16_CHAR PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_DOUBLE_2
#define PR128_OP_CAS_2_DOUBLE PR128_OP_CAS_2
#else
#define PR128_OP_CAS_2_DOUBLE PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_DOUBLE_2_VALUE
#define PR128_OP_CAS_VALUE_2_DOUBLE PR128_OP_CAS_VALUE_2
#else
#define PR128_OP_CAS_VALUE_2_DOUBLE PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_INT_4
#define PR128_OP_CAS_4_INT PR128_OP_CAS_4
#else
#define PR128_OP_CAS_4_INT PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_INT_4_VALUE
#define PR128_OP_CAS_VALUE_4_INT PR128_OP_CAS_VALUE_4
#else
#define PR128_OP_CAS_VALUE_4_INT PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_PTR_2
#define PR128_OP_CAS_2_PTR PR128_OP_CAS_2
#else
#define PR128_OP_CAS_2_PTR PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_PTR_2_VALUE
#define PR128_OP_CAS_VALUE_2_PTR PR128_OP_CAS_VALUE_2
#else
#define PR128_OP_CAS_VALUE_2_PTR PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_UINT_4
#define PR128_OP_CAS_4_UINT PR128_OP_CAS_4
#else
#define PR128_OP_CAS_4_UINT PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_CAS_UINT_4_VALUE
#define PR128_OP_CAS_VALUE_4_UINT PR128_OP_CAS_VALUE_4
#else
#define PR128_OP_CAS_VALUE_4_UINT PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_8_16
#define PR128_OP_LOAD_16_8 PR128_OP_LOAD_16
#else
#define PR128_OP_LOAD_16_8 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_16_8
#define PR128_OP_LOAD_8_16 PR128_OP_LOAD_8
#else
#define PR128_OP_LOAD_8_16 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_32_4
#define PR128_OP_LOAD_4_32 PR128_OP_LOAD_4
#else
#define PR128_OP_LOAD_4_32 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_64_2
#define PR128_OP_LOAD_2_64 PR128_OP_LOAD_2
#else
#define PR128_OP_LOAD_2_64 PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_CHAR_16
#define PR128_OP_LOAD_16_CHAR PR128_OP_LOAD_16
#else
#define PR128_OP_LOAD_16_CHAR PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_INT_4
#define PR128_OP_LOAD_4_INT PR128_OP_LOAD_4
#else
#define PR128_OP_LOAD_4_INT PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_PTR_2
#define PR128_OP_LOAD_2_PTR PR128_OP_LOAD_2
#else
#define PR128_OP_LOAD_2_PTR PR128_OP_UNIMPLEMENTED
#endif

#ifdef CK_F_PR_LOAD_UINT_4
#define PR128_OP_LOAD_4_UINT PR128_OP_LOAD_4
#else
#define PR128_OP_LOAD_4_UINT PR128_OP_UNIMPLEMENTED
#endif

#define PR128_OPS_GROUP1(X, ...) \
	X(CAS_16,       __VA_ARGS__) \
	X(CAS_VALUE_16, __VA_ARGS__) \
	X(LOAD_16,      __VA_ARGS__)
#define PR128_OPS_GROUP2(X, ...) \
	X(CAS_8,        __VA_ARGS__) \
	X(CAS_VALUE_8,  __VA_ARGS__) \
	X(LOAD_8,       __VA_ARGS__)
#define PR128_OPS_GROUP3(X, ...) \
	X(CAS_4,        __VA_ARGS__) \
	X(CAS_VALUE_4,  __VA_ARGS__) \
	X(LOAD_4,       __VA_ARGS__)
#define PR128_OPS_GROUP4(X, ...) \
	X(CAS_2,        __VA_ARGS__) \
	X(CAS_VALUE_2,  __VA_ARGS__) \
	X(LOAD_2,       __VA_ARGS__)
#define PR128_OPS_GROUP5(X, ...) \
	X(CAS_2,        __VA_ARGS__)

#define PR128_OP_EXPANDER(OP, X, ...) \
	PR128_OP_##OP(X, __VA_ARGS__)

#define PR128_OPS_LIST(X, ...) \
	PR128_OPS_GROUP1(PR128_OP_EXPANDER, X, __VA_ARGS__) \
	PR128_OPS_GROUP2(PR128_OP_EXPANDER, X, __VA_ARGS__) \
	PR128_OPS_GROUP3(PR128_OP_EXPANDER, X, __VA_ARGS__) \
	PR128_OPS_GROUP4(PR128_OP_EXPANDER, X, __VA_ARGS__)
	/* GROUP5 is a subset of GROUP4 */

/*        FT      N   ... */
#define PR128_F_TYPES_LIST(X, ...) \
	X(8,      16, __VA_ARGS__) \
	X(16,     8,  __VA_ARGS__) \
	X(32,     4,  __VA_ARGS__) \
	X(64,     2,  __VA_ARGS__) \
	X(CHAR,   16, __VA_ARGS__) \
	X(DOUBLE, 2,  __VA_ARGS__) \
	X(INT,    4,  __VA_ARGS__) \
	X(PTR,    2,  __VA_ARGS__) \
	X(UINT,   4,  __VA_ARGS__)

#define PR128_T_EXPANDER(FT, N, X, ...) \
	PR_##FT##_T(X, FT, N, __VA_ARGS__)

#define PR128_TYPES_LIST(X, ...) \
	PR128_F_TYPES_LIST(PR128_T_EXPANDER, X, __VA_ARGS__)

#define PR128_8_OPS_LIST      PR128_OPS_GROUP1
#define PR128_16_OPS_LIST     PR128_OPS_GROUP2
#define PR128_32_OPS_LIST     PR128_OPS_GROUP3
#define PR128_64_OPS_LIST     PR128_OPS_GROUP4
#define PR128_CHAR_OPS_LIST   PR128_OPS_GROUP1
#define PR128_DOUBLE_OPS_LIST PR128_OPS_GROUP5
#define PR128_INT_OPS_LIST    PR128_OPS_GROUP3
#define PR128_PTR_OPS_LIST    PR128_OPS_GROUP4
#define PR128_UINT_OPS_LIST   PR128_OPS_GROUP3
